language: node_js
node_js:
  - "0.10"
  - "0.12"
env:
  CODECLIMATE_REPO_TOKEN:
    secure: "LrQ/36OyEsVQGRfqu5l2OmZT5XzBdLFtmGLThRsjYaSEtJJQQkv+KNa31ZlXjeZscRCrVVKi0kkX2QFc668n6GGr10dpeGlaQjZRPv19DqApaWEayPhNXveZxyv9bfGVSefi4k0W6pIh4CinFpu+VAMQlBzj/FodEp+i0x4KhQm12gapdbsZhcBanubAhdQdoHGQZ4aLk0bEElagnZFzIcYemNhP6bkpdcEzYJoNaeA92mvEStyb9VFQxYGKNqFaEZnwD9IYkx2p0jHWQZgzoBz5GKuWy39iZxUAwkO01VFS0kLeNuJAzMDqAeTmbwR2XXimJ0IIxOFw2mzhozmZu6x1enBv0WBCd/jGuceHe/KAZBiGihUmGvtezxrPL+MMwkW/KMwfKqv5DptplkHvPy9X+YwB+H8IFULmX19Tm95UT2IXs/alnJMJW4ET263kdpMaPSIJJHEOz+4e/N9iItFp/gUYsoNJTxAhTQJ5kB4FDRNKO49BQSgiF7rMd6EV6Mt++HU9dhh68XoJ6HB2HSi8+4K+0W2F6mi/n/5291ey4OlOJ3ayUpgveezVXS/7DEBQIyb4fYb0H2H1R+Bljinzy55W9By4fBz/XpMAgtyijbluITODhkXqzRXTWP1hQ/XFLTdqx/nH4ouEp8HVec/yww/xphzwTcDnBCj6O5k="

sudo: false

before_script: "npm install codeclimate-test-reporter"

script: "npm run-script test-ci"
